# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dhorvath/git/eecs/eecs645/HW08_source_files/HW08_source_files/06_Aux_Units/test_project/test_project.cache/wt [current_project]
set_property parent.project_path C:/Users/dhorvath/git/eecs/eecs645/HW08_source_files/HW08_source_files/06_Aux_Units/test_project/test_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
read_vhdl -library xil_defaultlib C:/Users/dhorvath/git/eecs/eecs645/HW08_source_files/HW08_source_files/06_Aux_Units/sign_extend.vhd
synth_design -top sign_extend -part xc7a200tfbg676-2
write_checkpoint -noxdef sign_extend.dcp
catch { report_utilization -file sign_extend_utilization_synth.rpt -pb sign_extend_utilization_synth.pb }
